[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "4JSbnmWnAmRfaCWeZwFHWJrakYgrqtkXRqZ6MN4o9KiE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vladygk/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
